language: cpp
os: linux
dist: xenial

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-8

matrix:
  include:
    - compiler: gcc
      env:
        - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"
    - compiler: clang

before_install:
  - eval "${MATRIX_EVAL}"

script:
  - mkdir -p ./build && cd ./build
  - cmake -DCMAKE_BUILD_TYPE=Release -DLIBIPC_BUILD_TESTS=ON ..
  - make -j`nproc`
  - export LD_LIBRARY_PATH=./lib:$LD_LIBRARY_PATH && ./bin/test-ipc

notifications:
  slack:
    on_success: never
    on_failure: never
